name: 'C++ CI'

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev doxygen graphviz cmake build-essential

      - name: Build Google Test libraries
        run: |
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp *.a /usr/lib/

      - name: Configure project with CMake
        run: cmake . -DPATCH_VERSION=${{ github.run_number }} -DWITH_BOOST_TEST=ON

      - name: Build project
        run: cmake --build .

      - name: Run Google Tests
        run: ctest --output-on-failure

      - name: Find generated .deb files
        run: find . -name '*.deb' -ls

      - name: Build package
        run: cmake --build . --target package

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./orm_database-0.0.${{ github.run_number }}-Linux.deb
          asset_name: orm_database-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package
